nodeLinker: pnp
installConfig:
  pnp: true
  defaultLanguage: "javascript"
  nodeLinker: "node-modules"
nmMode: "classic"
plugins:
  - node-modules
  - esbuild
supportedArchitectures:
  - "linux-x64"
  - "darwin-x64"

